### PR TITLE
Git sub module for organization and openzeppelin-solidity npm for safemath

### LINKED ISSUE #197: Use git-submodules to include SafeMath and Organized contracts in openst-contracts
**Use git-submodules to include the following contracts**

- SafeMath.sol
- Organized.sol

**Following is the proposal:**
1. Remove the existing implementation of the above contracts.
2. Use git-submodules to include Organized contract in the project from `OpenST/organization-contracts`.
3.  Use git-submodules to include SafeMath contract in the project from < will be updated >

### PR DESCRIPTION
**Pull request by 0xsarvesh**
fixes #197 

This PR does the following things: 
1. Added organization contracts as a git submodule
2. Added openzeppelin-solidity npm as a dependency for `SafeMath.sol`
3. Deleted organization contracts and safemath. 

@reviewer Please read the discussion about npm module Vs git submodule on the ticket #197

### CODE REVIEW

**Review by schemar — DISMISSED** [review]
Very nice!! :shipit: 

@sarvesh-ost you can rebase on latest `develop` (or merge); then travis will skip slither. Their docker image is currently broken: https://github.com/crytic/eth-security-toolbox/issues/9

**Comment by 0xsarvesh** [comment]
> Very nice!! :shipit:
> 
> @sarvesh-ost you can rebase on latest `develop` (or merge); then travis will skip slither. Their docker image is currently broken: [crytic/eth-security-toolbox#9](https://github.com/crytic/eth-security-toolbox/issues/9)

Thank you 🙌  
Merged the latest develop into this branch, Travis is now green ✅

**Comment by schemar** [comment]
Checking!

**Review by schemar — APPROVED** [review]
Love it :shipit:

**Pull request merged**
