### PR TITLE
Add FirewalledRule

### LINKED ISSUE #199: Repository should provide abstract firewall contract
ℹ️ Look at the parent epic for most of the details: #193

## Story

As a consumer of the package
I want to have a re-usable firewall available
Because I want to limit access to some of my rules

## Scenarios

Given that I implement a rule
When I extend the firewall
Then my rule can check for `tx.origin` to be a registered worker with an organisation

## Info

The info is in the epic #193

This ticket is only concerned with:

* Providing the abstract firewall contract that provides the modifier.
* Making sure the firewall can be turned off by the organization.
* Testing.

### PR DESCRIPTION
**Pull request by schemar**
I added a FirewalledRule which can be extended in order to restrict
relaying of meta-transactions to organization workers.
The rule that is to be restricted must extend the FirewalledRule and add
the modifier `firewalled` to all relevant functions.

For testing I created two test contract files. One that uses the
modifier, and one that calls the one that uses the modifier. Required in
order to simulate rules calling on each other and checking for the
relayer.

Added a step to manually install npx inside docker until the docker
image is fixed. The problem is reported and confirmed at
https://github.com/crytic/eth-security-toolbox/issues/8

Fixes #199

### CODE REVIEW

**Comment by schemar** [comment]
Crytic fixed the docker image, I should test and remove the extra line before merging!

**Comment by schemar** [comment]
When they fixed the previously reported bug, it seems they broke something else. I made a new report: https://github.com/crytic/eth-security-toolbox/issues/9

Waiting for an update, as this cannot be fixed with a workaround.

**Review by pgev — DISMISSED** [review]
Looks good to me. Once Travis fixed we could merge it.

**Comment by schemar** [comment]
Travis CI cannot cache docker images (https://docs.travis-ci.com/user/caching/#things-not-to-cache):
> Docker images are not cached, because we provision a brand new virtual machine for every build.

**Comment by schemar** [comment]
@pgev can you please have a look? I removed slither from `make:all`. I cannot get slither work with the eth-security-toolbox.

**Review by pgev — APPROVED** [review]
Approving. I've also subscribed to the ticket you've created (Slither fails to execute in latest docker tag). Once it's fixed we should create follow ticket to bring slither back.

**Pull request merged**
